### PR TITLE
feat: add client.threads.getThreadV2 method

### PR DESCRIPTION
**Pull request by fartinmartin**
Thanks for merging my last PR! Hoping to add one more method, this time to support getting the metadata of a Thread via [getThreadV2](https://quip.com/dev/automation/documentation/current#operation/getThreadV2). Let me know if I should tweak anything!

### CODE REVIEW

**Comment by piotrekwitkowski** [comment]
Great, thanks! I pushed the changes to npm too

**Comment by fartinmartin** [comment]
Hey @piotrekwitkowski, thanks for merging! I'm not seeing `client.threads.getThreadV2` populate in the npm package, is there a chance we missed a build step before publishing to npm? I could have also made a mistake in my PR, but just wanted to double check. Thanks again! 😊

**Comment by piotrekwitkowski** [comment]
@fartinmartin how about now with 1.3.1? https://www.npmjs.com/package/quip-api-typescript/v/1.3.1

**Comment by fartinmartin** [comment]
@piotrekwitkowski perfect, thank you! 🥳

**Pull request merged**
